version: "3.9"

services:

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASS=123
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - ./app-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123


volumes:
  app-db: