# Generated by Django 4.1.7 on 2023-03-06 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='original_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images.image'),
        ),
    ]
