# Generated by Django 4.1.7 on 2023-03-08 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_thumbnail_original_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateTimeField()),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
