# Generated by Django 4.1.7 on 2023-03-08 17:09

from django.db import migrations, models
import images.models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_imagetoken_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=images.models.upload_to, validators=[images.validators.check_file_size]),
        ),
    ]
