# Generated by Django 4.1.7 on 2023-03-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_thumbnail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
